# Generated by Django 3.1.4 on 2021-01-16 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210113_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavemodel',
            name='cur_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='leavemodel',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
