# Generated by Django 3.1.4 on 2021-01-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210122_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='degree_cert',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='empdata',
            name='tenth_cert',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='empdata',
            name='twelth_cert',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
