# Generated by Django 3.1.4 on 2021-01-16 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20210116_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavemodel',
            name='lid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='attendancemodel',
            name='status',
            field=models.TextField(choices=[('0', 'absent'), ('1', 'present')]),
        ),
        migrations.AlterField(
            model_name='leavemodel',
            name='eid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
