# Generated by Django 3.1.4 on 2021-01-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210122_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='status',
            field=models.TextField(choices=[('1', 'present'), ('0', 'absent')]),
        ),
    ]
