# Generated by Django 3.1.4 on 2021-01-16 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210116_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='status',
            field=models.TextField(choices=[('1', 'present'), ('0', 'absent')]),
        ),
        migrations.AlterField(
            model_name='leavemodel',
            name='lid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
