# Generated by Django 3.1.4 on 2021-01-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210116_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancemodel',
            name='status',
            field=models.TextField(choices=[('0', 'absent'), ('1', 'present')]),
        ),
    ]
