# Generated by Django 3.1.4 on 2021-01-17 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20210116_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavemodel',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='empmodel',
            name='eid',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leavemodel',
            name='eid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
