# Generated by Django 3.1.4 on 2021-01-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210122_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdata',
            name='status',
            field=models.TextField(default=False, max_length=500),
        ),
    ]
