# Generated by Django 3.1.4 on 2021-01-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210117_1129'),
        ('api', '0009_auto_20210122_1236'),
    ]

    operations = [
    ]
