# Generated by Django 3.1.4 on 2021-01-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20210122_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplist',
            name='e_status',
            field=models.BooleanField(default=False),
        ),
    ]
